function [ret, ret2]= login_mapi_flist
% ret : list 1xN : list of files
% ret2: list Nx2 : list of files and unzipped folders

% >> IMPORTANT: match this fn with "path_ini" in "login_mapi.m" <<

% April 2020, Jose Gaspar

% filenames to duplicate (a copy foreach lab group)
ret= {
'_MAPI_readme.txt', ...
... % 'git4all.zip', ...
... % 'git4grp.zip', ...
... % 'git.zip', ...
'lab00.zip', ...
... % 'lab01.zip', ...
... % 'lab02.zip', ...
... % 'lab1.zip', ...
... % 'lab1a.zip', ...
... % 'lab1c.zip', ...
... % 'lab1d.zip', ...
... % 'lab2a.zip', ...
... % 'lab2b.zip', ...
... % 'lab2.zip', ...
... % 'lab2_intro.zip', ...
... % 'lab2_sim_1_priority.zip', ...
... % 'lab2_sim_5philosophers_v3.zip', ...
... % 'lab2_sim_kb_v6.zip', ...
... % 'PN_editor_MATLAB_sim_and_Manual_v4.zip', ...  % not needed, is in the path
... % 'pn_to_plc_v4.zip', ...  % not needed, is in the path
... % 'spnbox.zip', ...        % not needed, is in the path
... % 'train1_PN_sim.zip', ...
... % 'train2_PN_to_PLC.zip', ...
};

% simplify zip names to define folder names
gsarLst= {
    '_v6.zip', ''; ...
    '_v4.zip', ''; ...
    '_v3.zip', ''; ...
    '.zip', ''; ...
    };
ret2= {};
for i= 1:length(ret)
    fname= ret{i};
    ret2{end+1,1}= fname;
    ret2{end,2}= '';
    for j= 1:size(gsarLst,1)
        ind= strfind( fname, gsarLst{j,1} );
        if ~isempty(ind)
            ret2{end,2}= strrep( fname, gsarLst{j,1}, gsarLst{j,2} );
            break
        end
    end
end
